version: '3.8'
services:
  app:
    build:
      context: /Users/ponhrithnhep/Documents/Coding_Projects/Sunrise_Assignment/Java_Spring_Assignment/assignment
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://java-spring-assignment:5432/sunrisedb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
    networks:
      - existing_network

networks:
  existing_network:
    driver: bridge

