version: '3.8'

services:
  db:
    image: postgres:15
    container_name: assignment-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sunrisedb
    networks:
      - existing_network

  app:
    build:
      context: .
    container_name: assignment-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sunrisedb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    depends_on:
      - db
    networks:
      - existing_network

networks:
  existing_network:
    driver: bridge
